"""update user_name to username for user table

Revision ID: 6706fc8b0643
Revises: fd4f409b8d29
Create Date: 2025-10-05 16:52:32.387176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6706fc8b0643'
down_revision: Union[str, Sequence[str], None] = 'fd4f409b8d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(), nullable=False))
    op.drop_constraint(op.f('user_user_name_key'), 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint(op.f('user_user_name_key'), 'user', ['user_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
